In [1]:
import numpy as np

Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 20, затем создайте массив состоящий из 5 элементов, начиная со 2 по порядку. Выведите значения обоих массивов при помощи функции print()

In [15]:
arr_1 = np.random.randint(1, 21, 10)
arr_2 = arr_1[1:6]
print(arr_1)
print(arr_2)

[16 13 12  7  5  3 16  9  4 18]
[13 12  7  5  3]


Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 0 до 20, затем создайте массив состоящий из элементов, начиная с третьего по порядку до последнего. Выведите значения обоих массивов при помощи функции print()

In [16]:
arr_1 = np.random.randint(1, 21, 10)
arr_2 = arr_1[2:]
print(arr_1)
print(arr_2)

[ 2  8  5  7 18  6  3 12 16  5]
[ 5  7 18  6  3 12 16  5]


Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 3 до 11, в котором 4 строки и 3 столбца. Затем создайте массив состоящий из элементов , второй и третьей строки и первого и второго столбца по порядку. Выведите значения обоих массивов при помощи функции print()

In [25]:
arr_1 = np.random.randint(3, 12, 12).reshape(4, 3)
arr_2 = arr_1[1:3, :2]
print(arr_1)
print(arr_2)

[[11 10  8]
 [ 5  9  3]
 [ 8 11  8]
 [ 3  3  4]]
[[ 5  9]
 [ 8 11]]


Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 0 до 9, в котором 4 строки и 6 столбцов. Затем создайте массив состоящий из элементов , которые больше числа 3. Выведите значения обоих массивов при помощи функции print()

In [31]:
arr_1 = np.random.randint(0, 10, 24).reshape(4, 6)
arr_2 = arr_1[arr_1>3]
print(arr_1)
print(arr_2)

[[5 4 8 4 9 6]
 [8 1 6 6 7 9]
 [5 9 2 5 9 3]
 [9 3 0 1 0 1]]
[5 4 8 4 9 6 8 6 6 7 9 5 9 5 9 9]
